In [9]:
import os
import sys
import csv
import pandas as pd
import numpy as np
import random
import os.path
from os import path

from skimage.color import rgb2hsv
import PIL
from PIL import Image

import deepforest
from deepforest import main

from pykml import parser

import geopandas as gpd
import fiona 
from bs4 import BeautifulSoup

In [2]:
am = pd.read_csv('/home/irene/ISEF-Project-2023/Data/AM.csv')
ll = pd.read_csv('/home/irene/ISEF-Project-2023/Data/Mappa_ailanto_Parco_Alta_Murgia_23.09.csv')

In [ ]:
Ones = []
Zeroes = []
for i in ll.index:
    x = ll["X"][i]
    y = ll["Y"][i]
    print(x)
    print(y)
    for j in am.index:
        u = am["Upper"][j].split(", ")
        l = am["Lower"][j].split(", ")
        if(float(y)<= float(u[0]) and float(y) >= float(l[0])):
            if(float(x) <= float(l[1]) and float(x) >= float(u[1])):
                if(Ones.count(am["Path"][j]) == 0):
                    Ones.append(am["Path"][j])
        else:
            if(Zeroes.count(am["Path"][j]) == 0):
                Zeroes.append(am["Path"][j])

16.3871511106883
40.9553915556676
16.3969764870561
40.957106925050795
16.396699435669902
40.9565056427753
16.3974691884181
40.9571173633962
16.5071279003474
40.9332262514913
16.2859665724195
40.9749106100111
16.2867159920759
40.9748458713497
16.4807883235972
40.9564972955169
16.4806117885656
40.9566063804063
16.2253912982706
40.981888058551604
16.2499660002037
41.0089181539372
16.240243779159698
40.9743338343942
16.250190539290198
41.006213871656996
16.2498581367159
41.008599832362
16.245147912681
40.9813074156846
16.164603606473598
41.039911652133796
16.307859635473
40.9743954861247
16.309366097781698
40.9753005534547

In [7]:
labels = [0]*len(Zeroes)
labels.extend([1]*len(Ones))
path_list = Zeroes+Ones

In [8]:
df = pd.DataFrame({'image_path': path_list, 'label': labels})
df

                                              image_path  label
0      /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
1      /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
2      /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
3      /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
4      /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
...                                                  ...    ...
25512  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25513  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25514  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25515  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25516  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1

[25517 rows x 2 columns]

In [9]:
df.to_csv('Output.csv')

In [34]:
df = pd.read_csv("/home/irene/ISEF-Project-2023/Output.csv")

In [35]:
l = []
for i in range(400):
    num = random.randint(0,25109)
    if(l.count(num)<=0):
        l.append(num)
l.sort()

In [36]:
l

[63,
 239,
 367,
 383,
 424,
 512,
 545,
 581,
 662,
 897,
 1013,
 1033,
 1036,
 1041,
 1142,
 1192,
 1334,
 1433,
 1551,
 1559,
 1633,
 1650,
 1750,
 1777,
 1792,
 1880,
 1887,
 2034,
 2181,
 2336,
 2379,
 2492,
 2512,
 2528,
 2538,
 2549,
 2556,
 2583,
 2656,
 2692,
 2714,
 2868,
 2892,
 2930,
 2992,
 3115,
 3155,
 3180,
 3220,
 3268,
 3339,
 3360,
 3369,
 3372,
 3384,
 3418,
 3432,
 3449,
 3485,
 3512,
 3545,
 3576,
 3592,
 3623,
 3683,
 3746,
 3868,
 3877,
 4034,
 4109,
 4229,
 4346,
 4440,
 4505,
 4519,
 4584,
 4625,
 4693,
 4707,
 4983,
 5005,
 5024,
 5071,
 5109,
 5206,
 5252,
 5338,
 5468,
 5486,
 5588,
 5673,
 5754,
 5834,
 5959,
 6057,
 6119,
 6154,
 6173,
 6279,
 6295,
 6381,
 6388,
 6398,
 6417,
 6424,
 6466,
 6657,
 6673,
 6726,
 6751,
 6796,
 6840,
 6941,
 6943,
 6966,
 7093,
 7215,
 7257,
 7269,
 7295,
 7395,
 7533,
 7559,
 7568,
 7582,
 7598,
 7669,
 7676,
 7711,
 7768,
 7812,
 7820,
 7921,
 7930,
 7977,
 7994,
 8188,
 8220,
 8250,
 8474,
 8479,
 8556,
 8585,
 8766,
 8776,
 8812,
 8913,
 8933,
 8934,
 9103,
 9107,
 9114,
 9214,
 9243,
 9610,
 9646,
 9694,
 9700,
 9878,
 9880,
 9944,
 9949,
 10002,
 10097,
 10232,
 10287,
 10302,
 10555,
 10556,
 10567,
 10596,
 10660,
 10722,
 10775,
 10787,
 10853,
 10886,
 10925,
 10966,
 11047,
 11128,
 11160,
 11198,
 11223,
 11395,
 11466,
 11515,
 11596,
 11636,
 11731,
 11737,
 11740,
 11789,
 11849,
 11862,
 11896,
 11923,
 11998,
 12024,
 12027,
 12076,
 12184,
 12192,
 12252,
 12345,
 12631,
 12647,
 12677,
 12718,
 12743,
 12814,
 12988,
 12991,
 13066,
 13071,
 13075,
 13076,
 13134,
 13321,
 13519,
 13623,
 13632,
 13651,
 13733,
 13743,
 13864,
 13980,
 14049,
 14090,
 14210,
 14324,
 14364,
 14374,
 14405,
 14410,
 14634,
 14659,
 14771,
 14919,
 14924,
 15070,
 15121,
 15131,
 15215,
 15281,
 15397,
 15480,
 15529,
 15596,
 15835,
 15897,
 15898,
 15935,
 15937,
 15955,
 16016,
 16075,
 16246,
 16260,
 16358,
 16378,
 16391,
 16527,
 16576,
 16692,
 16780,
 16807,
 16871,
 17000,
 17033,
 17077,
 17089,
 17148,
 17205,
 17220,
 17332,
 17359,
 17399,
 17416,
 17424,
 17532,
 17585,
 17740,
 17819,
 17834,
 18015,
 18103,
 18153,
 18167,
 18200,
 18217,
 18307,
 18448,
 18473,
 18552,
 18580,
 18702,
 18730,
 18732,
 18838,
 18871,
 18992,
 19007,
 19087,
 19164,
 19287,
 19302,
 19365,
 19407,
 19412,
 19466,
 19555,
 19609,
 19733,
 19806,
 19924,
 20107,
 20197,
 20225,
 20254,
 20283,
 20322,
 20364,
 20371,
 20387,
 20395,
 20444,
 20447,
 20536,
 20588,
 20714,
 20798,
 20867,
 20929,
 21035,
 21044,
 21093,
 21178,
 21236,
 21276,
 21281,
 21393,
 21459,
 21462,
 21522,
 21568,
 21599,
 21618,
 21637,
 21765,
 21769,
 21810,
 21852,
 21970,
 22005,
 22020,
 22104,
 22141,
 22395,
 22546,
 22649,
 22716,
 22902,
 22907,
 22924,
 23047,
 23139,
 23161,
 23302,
 23305,
 23320,
 23355,
 23475,
 23503,
 23537,
 23612,
 23642,
 23678,
 23864,
 23958,
 24076,
 24125,
 24257,
 24353,
 24478,
 24514,
 24546,
 24547,
 24560,
 24623,
 24645,
 24701,
 24755,
 24803,
 24828,
 24896,
 25081]

In [38]:
for i in range (25109):
    if (l.count(i)<=0):
        df = df.drop(i)

In [39]:
df

       Unnamed: 0                                         image_path  label
63             63  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
239           239  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
367           367  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
383           383  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
424           424  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      0
...           ...                                                ...    ...
25512       25512  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25513       25513  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25514       25514  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25515       25515  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1
25516       25516  /home/irene/ISEF-Project-2023/Data/Alta Murgia...      1

[805 rows x 3 columns]

In [40]:
df.to_csv('PreHDF5.csv')

In [17]:
#data imbalance --> very common, novelty, because such problems exist sample 400 (Pandas reset index)
#Dice Balance loss --> pytorch 
#Data augmentation: add variety and quantity
from sklearn.model_selection import train_test_split
train_df, temp_df = train_test_split(df, test_size = 0.4, stratify = df['label'], random_state = 0)
val_df, test_df = train_test_split(temp_df, test_size = 0.5, stratify = temp_df['label'], random_state = 0)